### PR TITLE
Add keymaps supplied in issues

### PR DESCRIPTION
**Pull request by jzohrab**
https://github.com/kernc/logkeys/issues/88 - Ubuntu 12.04 en US
https://github.com/kernc/logkeys/issues/119 - French Canadian
https://github.com/kernc/logkeys/issues/121 - Swiss German
https://github.com/kernc/logkeys/issues/123 - Polish

There are a few Arabic maps that I didn't include.

I haven't tested these maps myself, I'm not able to - I'd like to add a sanity check/smoke test that parses the keymaps to ensure that there are no parsing errors, at least.

If we merge this, we can close the above issues.

### CODE REVIEW

**Comment by kernc** [comment]
The two attached de_CH keymaps in #121 and #102 are not the same. How did you decide for one over the other?

**Comment by jzohrab** [comment]
I'm not sure how to check these, actually, and went on assumption that the later one was preferred.  We could include them both, with de_CH_1 and de_CH_2.

**Comment by jzohrab** [comment]
ps - this is why we should continue doing what we're doing - PRs, rather than me committing directly to master or accepting my own PRs.  Let me know if this gets irksome.

**Comment by kernc** [comment]
I examined them manually, and while I can't be certain either, they both look pretty similar compared to e.g. _de.map_, and the one you included seems somewhat more reasonable (has `'`, `<PrtSc>`, ...).

**Comment by kernc** [comment]
What are you talking about; it's super fun! :stuck_out_tongue:

**Comment by jzohrab** [comment]
It is, isn't it! :-)

**Pull request merged**
